services:
  # Serviço do PHP
  app:
    image: php:8.5-fpm-alpine
    container_name: php-app-2
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped

  # Serviço do Nginx
  web:
    image: nginx:alpine
    container_name: nginx-server-2
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: unless-stopped
